"""set unique constraint on publications.name
Revision ID: 7299a2b770a2
Revises: 7a389eb5c967
Create Date: 2025-09-22 18:43:34.561468

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7299a2b770a2"
down_revision: Union[str, Sequence[str], None] = "7a389eb5c967"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "publications", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "publications", type_="unique")
    # ### end Alembic commands ###
